const navItems=document.querySelectorAll(".nav-item"),toast=document.getElementById("toast"),openButtons=document.querySelectorAll(".open-island"),islandView=document.getElementById("islandView"),dashboard=document.getElementById("dashboard"),quickSearch=document.getElementById("quickSearch"),toggleSearch=document.getElementById("toggleSearch"),backMap=document.getElementById("backMap"),searchInput=document.getElementById("searchInput"),filterBtn=document.getElementById("filterBtn"),flowWrapper=document.getElementById("flowWrapper"),flowImage=document.getElementById("flowImage"),miroFrame=document.getElementById("miroFrame"),fullBtn=document.getElementById("fullBtn"),islandTitle=document.getElementById("islandTitle"),islandDesc=document.getElementById("islandDesc"),pdfLink=document.getElementById("pdfLink"),brandHome=document.getElementById("brandHome"),viewerPill=document.getElementById("viewerPill");
let currentIsland="sem";let zoom=.34;
function showToast(m){toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2200)}
function data(){return window.ILHAS[currentIsland]}
function isMiro(){return !!data().miro}
function applyZoom(){if(isMiro())return;flowImage.style.transform=`scale(${zoom})`;flowImage.style.marginRight=`${flowImage.naturalWidth*(zoom-1)}px`;flowImage.style.marginBottom=`${flowImage.naturalHeight*(zoom-1)}px`}
function centerTop(){if(isMiro())return;setTimeout(()=>{flowWrapper.scrollLeft=Math.max(0,(flowWrapper.scrollWidth-flowWrapper.clientWidth)/2);flowWrapper.scrollTop=0},100)}
function setViewerMode(){const d=data();if(d.miro){flowWrapper.classList.add("miro-mode");flowImage.style.display="none";flowImage.removeAttribute("src");miroFrame.style.display="block";if(miroFrame.src!==d.miro)miroFrame.src=d.miro;}else{flowWrapper.classList.remove("miro-mode");miroFrame.style.display="none";miroFrame.src="";flowImage.style.display="block";}}
function setIsland(key, open=true){currentIsland=key;const d=data();islandTitle.textContent=d.title;islandDesc.textContent=d.desc;viewerPill.textContent=key==="baseclt"?"Material ativo":"Ilha ativa";if(d.pdf){pdfLink.href=d.pdf;pdfLink.style.display="inline-flex";}else{pdfLink.removeAttribute("href");pdfLink.style.display="none";}navItems.forEach(i=>i.classList.toggle("active",i.dataset.island===key));if(open){dashboard.classList.add("hidden");islandView.classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}setViewerMode();if(!d.miro){flowImage.src=d.image;flowImage.width=d.width;flowImage.height=d.height;zoom=d.fitZoom;setTimeout(()=>{applyZoom();centerTop()},150)}}
flowImage.addEventListener("load",()=>{applyZoom();centerTop()});
navItems.forEach(item=>{item.addEventListener("click",()=>{if(item.classList.contains("locked")){showToast("Esta ilha será adicionada em breve.");return}setIsland(item.dataset.island,true)})});
openButtons.forEach(btn=>btn.addEventListener("click",()=>setIsland(btn.dataset.open,true)));
function showDashboard(){islandView.classList.remove("active");dashboard.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
backMap.addEventListener("click",showDashboard);
brandHome.addEventListener("click",showDashboard);
toggleSearch.addEventListener("click",()=>{quickSearch.classList.toggle("hidden");toggleSearch.textContent=quickSearch.classList.contains("hidden")?"Mostrar Pesquisa":"Ocultar Pesquisa"});
fullBtn.addEventListener("click",()=>{if(flowWrapper.requestFullscreen)flowWrapper.requestFullscreen()});
let drag=false,startX,startY,scrollLeft,scrollTop;
flowWrapper.addEventListener("mousedown",e=>{if(isMiro())return;drag=true;startX=e.pageX-flowWrapper.offsetLeft;startY=e.pageY-flowWrapper.offsetTop;scrollLeft=flowWrapper.scrollLeft;scrollTop=flowWrapper.scrollTop});
flowWrapper.addEventListener("mouseleave",()=>drag=false);flowWrapper.addEventListener("mouseup",()=>drag=false);flowWrapper.addEventListener("mousemove",e=>{if(!drag||isMiro())return;e.preventDefault();const x=e.pageX-flowWrapper.offsetLeft,y=e.pageY-flowWrapper.offsetTop;flowWrapper.scrollLeft=scrollLeft-(x-startX);flowWrapper.scrollTop=scrollTop-(y-startY)});
filterBtn.addEventListener("click",()=>{const term=searchInput.value.trim().toLowerCase();if(!term){showToast("Digite algo para pesquisar.");return}if(term.includes("fgts"))setIsland("fgts",true);else if(term.includes("pend"))setIsland("pendentes",true);else if(term.includes("suporte"))setIsland("suporte",true);else if(term.includes("piloto"))setIsland("cltpiloto",true);else if(term.includes("clt")||term.includes("base"))setIsland("baseclt",true);else if(term.includes("autoriz"))setIsland("sem",true);else setIsland(currentIsland,true);showToast("Resultado aberto para: "+term)});
searchInput.addEventListener("keydown",e=>{if(e.key==="Enter")filterBtn.click()});
setIsland("sem",false);
